delta_robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  delta_joint1_effort_controller:
    type: effort_controllers/JointPositionController
    joint: joint1
    pid: {p: 1.0, i: 0.0, d: 0.0}
  
    #pid: {p: 100.0, i: 0.01, d: 10.0}


  delta_joint2_effort_controller:
    type: effort_controllers/JointPositionController
    joint: joint2
    pid: {p: 1.0, i: 0.0, d: 0.0}
  
  delta_joint3_effort_controller:
    type: effort_controllers/JointPositionController
    joint: joint3
    pid: {p: 1.0, i: 0, d: 0}
